name: porfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_syntax_view: ^4.1.7
  google_fonts: ^6.2.1
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
